### ISSUE TITLE
SqlRs: The helper function Restart-ReportingServicesService timeouts

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#1114]
#### Details of the scenario you tried and the problem that is occurring
When restarting the Reporting Services service with the helper function `Restart-ReportingServicesService` is is using `Restart-Service`. The problem seems that `Restart-Service` timeouts on the build worker sometimes probably because it takes to long to start the service. 

This is show here: https://ci.appveyor.com/project/johlju/sqlserverdsc?fullLog=true#L8294

#### The DSC configuration that is using the resource (as detailed as possible)
The configuration for the integration test for SqlRs.

#### Version of the operating system and PowerShell the target node is running
Windows Server 2016, WMF 5.1

#### SQL Server edition and version the target node is running
SQL Server 2016 SP1

#### What SQL Server PowerShell modules, and which version, are present on the target node.
n/a

#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch
Dev

**Comment by johlju** [comment]
Seems this wasn't what I thought it was. The event log in the AppVeyor is reporting

```
Log Name:      Application
Source:        Report Server Windows Service (DSCRS2016)
Date:          4/21/2018 11:28:53 PM
Event ID:      121
Task Category: Startup/Shutdown
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      APPVYR-WIN
Description:
The Remote Procedure Call (RPC) service failed to start.
```

```
Log Name:      Application
Source:        Report Server Windows Service (DSCRS2016)
Date:          4/21/2018 11:28:53 PM
Event ID:      140
Task Category: Startup/Shutdown
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      APPVYR-WIN
Description:
The application domain WindowsService_0 failed to initialize. Error: The endpoint cannot be created.
```

```
Log Name:      Application
Source:        Report Server Windows Service (DSCRS2016)
Date:          4/21/2018 11:29:02 PM
Event ID:      140
Task Category: Startup/Shutdown
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      APPVYR-WIN
Description:
The application domain DefaultDomain failed to initialize. Error: RPC Server failed to start..
```

```
Log Name:      Application
Source:        SQL Server Reporting Services (DSCRS2016)
Date:          4/21/2018 11:29:02 PM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      APPVYR-WIN
Description:
Service cannot be started. System.Exception: Default appdomain failed to initialize.
   at Microsoft.ReportingServices.Library.ServiceAppDomainController.Start()
   at Microsoft.ReportingServices.Library.ReportService.OnStart(String[] args)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
```

**Comment by johlju** [comment]
It seems the services is restarted to quickly, so something isn't quite ready to service the startup request. If I add a timeout of 60 seconds the service is started properly. Maybe that time can be shortened.

**Comment by johlju** [comment]
Many hits on a search suggest to add a registry key `ServicesPipeTimeout` with a higher timeout value. This is one of those articles [Reporting Services not starting, the service failed or the service did not start in a timely fashion](https://coresql.com/2016/05/23/reporting-services-not-starting-the-service-failed-or-the-service-did-not-start-in-a-timely-fashion/), and here is another [How to Work Around Configuration Service Startup Issues](https://technet.microsoft.com/en-us/library/hh519702(v=sc.12).aspx). But setting this registry key didn't seem to have any affect.

Only solution was to wait between stopping the services and starting the service. If anyone knows anything more around this, please enlighten me 😃 

I will send in a PR shortly that will wait 30 seconds before starting the service after it has been configured.
